[build]
  command = "npm run build"
  functions = "functions"
  publish = "build"

  [dev]
    framework = "#custom"
    command = "npm run dev:snowpack"
    targetPort = 8079
    port = 8080
    publish = "public"
    jwtRolePath = "app_metadata.authorization.roles"
    autoLaunch = true
